title: "Technology Blog"
description: "Bioinformatics, algorithms, workflows, and notes"
theme: jekyll-theme-hacker

markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# GitHub Pages 默认设置
plugins:
  - jekyll-feed
  - jekyll-seo-tag
