title: Shixiang's Blog
author: Shixiang
email: shixiangy130@gmail.com
description: >
  Records of algorithms, bioinformatics, workflow optimization, and study notes.

theme: minima


minima:
  skin: classic  

markdown: kramdown
highlighter: rouge

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
